spring:
  application:
    name: ConsumerDataService
  data:
    mongodb:
      host: localhost
      port: 27018
      database: GringottsBank_Consumer
      username: gringotts
      password: goldenkey123
      authentication-database: admin
  kafka:
    bootstrap-servers: localhost:9092

topic:
  client:
    name: clients3

server:
  port: 8082

logging:
  file:
    name: ./logs/consumer.log
  pattern:
    file: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","service":"ConsumerDataService","thread":"%t","logger":"%c","message":"%m"}%n'
